version: '2'
services:
    django:
        build: .
        ports:
            - "${DJANGO_PORT}:8000"
        volumes:
            - "./static:/static"
        depends_on:
            - "postgres"
            - "celery"
        environment:
            - "DJANGO_SETTINGS_MODULE=popit_ng.settings_docker"
            - "POSTGRES_PASSWORD"
    celery:
        build: .
        command: "celery worker -A popit_ng"
        environment:
            - "DJANGO_SETTINGS_MODULE=popit_ng.settings_docker"
            - "POSTGRES_PASSWORD"
        depends_on:
            - "redis"
            - "postgres"
            - "elastic"
    postgres:
        image: "postgres:alpine"
        volumes:
            - "./pgdata:/var/lib/postgresql/data"
        environment:
            - "POSTGRES_PASSWORD"
    redis:
        image: "redis:alpine"
    elastic:
        image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.0"
        volumes:
            - "./esdata:/usr/share/elasticsearch/data"
        environment:
            - "xpack.security.enabled=false"
